#!/bin/bash
# Use colors, but only if connected to a terminal, and that terminal
# supports them.
if which tput >/dev/null 2>&1; then
    ncolors=$(tput colors)
fi
if [ -t 1 ] && [ -n "$ncolors" ] && [ "$ncolors" -ge 8 ]; then
  RED="$(tput setaf 1)"
  GREEN="$(tput setaf 2)"
  YELLOW="$(tput setaf 3)"
  BLUE="$(tput setaf 4)"
  BOLD="$(tput bold)"
  NORMAL="$(tput sgr0)"
else
  RED=""
  GREEN=""
  YELLOW=""
  BLUE=""
  BOLD=""
  NORMAL=""
fi

# Only enable exit-on-error after the non-critical colorization stuff,
# which may fail on systems lacking tput or terminfo
set -e

if [ ! -n "$MYBASH" ]; then
  MYBASH=$HOME/.bash_profile.d
fi

if [ ! -d "$MYBASH" ]; then
  printf "${YELLOW}.bash_profile.d is not installed.${NORMAL}\n"
  exit
fi

printf "${BLUE}Removing $MYBASH...${NORMAL}\n"

rm -rf $MYBASH

printf "${BLUE}Removing .bash_profile patch${NORMAL}\n"

sed -i.bak '/^# \.bash_profile\.d options/d' ~/.bash_profile
sed -i.bak '/^export MYBASH=/d' ~/.bash_profile
sed -i.bak '/^source \$MYBASH\/init\.sh/d' ~/.bash_profile
sed -i.bak '/^export _DEVELOPMENT_BASE_PATH/d' ~/.bash_profile

rm ~/.bash_profile.bak

printf "${GREEN}bash_profile.d is successfully uninstalled${NORMAL}\n"
