#!/bin/bash
SCRIPT_PATH="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_PATH/set_colors.sh"

if [ ! -n "$MYBASH" ]; then
  MYBASH=$HOME/.bash_profile.d
fi

if [ ! -d "$MYBASH" ]; then
  printf "${YELLOW}.bash_profile.d is not installed.${NORMAL}\n"
  exit
fi

printf "${BLUE}Removing $MYBASH...${NORMAL}\n"

rm -rf $MYBASH

printf "${BLUE}Removing .bash_profile patch${NORMAL}\n"

sed -i.bak '/^# \.bash_profile\.d options/d' ~/.bash_profile
sed -i.bak '/^export MYBASH=/d' ~/.bash_profile
sed -i.bak '/^source \$MYBASH\/init\.sh/d' ~/.bash_profile
sed -i.bak '/^export _DEVELOPMENT_BASE_PATH/d' ~/.bash_profile

rm ~/.bash_profile.bak

printf "${GREEN}bash_profile.d is successfully uninstalled${NORMAL}\n"
